[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = 'pymath-dot'
requires-python = '>=3.10.0'
version = '0.1.1'
dependencies = [
    'sympy>=1.9'
]

[project.urls]
repository = 'https://github.com/ded-otshelnik/pymath'